# Generated by Django 3.2.7 on 2021-09-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210913_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='details',
        ),
    ]
